name: pemf
favicon: null
layout_spectrum: 0.96748
typography_spectrum: 0.68941
title: Health Electric
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1c24'
    - '#29b34b'
    - '#008000'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.5
  lightness: 0.46237339824438095
  saturation: 0.6728259802330285
  rhythmicContrast: 0.5
purpose: []
